### ISSUE TITLE
Cannot install Neptune using Tidal from the Microsoft Store

### ISSUE THREAD

**Issue by kegobass** [uwu/neptune#1]
Hello.  I am trying to install Neptune and though it says it's successful, the menu never shows up in Tidal.  I believe it could be related to using the Microsoft Store version of Tidal versus the standalone version.  I was curious if this is a known issue.  Thanks!

**Comment by twnlink** [comment]
There's a very good chance that the neptune installer does not work with the microsoft store version of TIDAL, but it also can fail if you try to install neptune while TIDAL is running.

**Comment by kegobass** [comment]
I confirmed it works perfectly with the standalone Tidal app.  Thanks!
