### ISSUE TITLE
Last two updates to Tidal have wiped Neptune

### ISSUE THREAD

**Issue by heartmeeting** [uwu/neptune#10]
Hi - each of the last two updates to Tidal have lost the Neptune add-in and I've had to reinstall it. Once reinstalled the plugins I had previously added were still there. Whilst this isn't a big deal - reinstalling Neptune being dead simple - I just wondered if you were aware of this and if it's avoidable. Thanks!

**Comment by twnlink** [comment]
I was never able to exactly check for this but I sort've assumed it was the case. At some point I'll figure out a solution, though at the moment I'm uncertain.

**Comment by heartmeeting** [comment]
You're a star - closing the issue on that basis.

**Comment by heartmeeting** [comment]
You're a star - closing the issue on that basis.
