### ISSUE TITLE
Typescript types use enums

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune#12]
Hia, the ts types are awesome. Would it be possible to instead of using string literals use Enum types where applicable?

Eg changing this:
```ts
mediaMetadata?: {
	tags?: ("LOSSLESS" | "SONY_360RA" | "DOLBY_ATMOS" | "HIRES_LOSSLESS" | "MQA")[];
};
```

to
```ts
enum MetadataTags {
	Lossless = "LOSSLESS", 
	Sont360 = "SONY_360RA", 
	Atmos= "DOLBY_ATMOS", 
	HiRes = "HIRES_LOSSLESS", 
	MQA = "MQA"
}
mediaMetadata?: {
	tags?: MetadataTags[];
};
```

**Comment by twnlink** [comment]
The type definitions for TIDAL's APIs are automatically generated.

**Comment by Inrixia** [comment]
Ah, what generator are you using? They generally have a option to also provide enums

**Comment by Inrixia** [comment]
@relative yep I know. I'm asking what generator is used as generally there is a flag you can set to use enuns in place of string literals.

**Comment by relative** [comment]
[dts-bundle-generator](https://github.com/uwu/neptune/blob/master/types/tidal/index.d.ts#L1)

**Comment by Inrixia** [comment]
Welp looks like it doesn't support enum output.

Manuly casting type safe enums will have to do.

Thanks for the help.
