### ISSUE TITLE
Plugin settings resetting after app restart

### ISSUE THREAD

**Issue by GOAT-Preacher** [uwu/neptune#13]
While using this Plugin https://inrixia.github.io/neptune-plugins/TidalTags, the plugin-specific settings always reset after restarting the app. Disabling the entire plugin persists after a restart.

**Comment by twnlink** [comment]
This is a bug in @Inrixia's plugin on the lines linked below:
https://github.com/Inrixia/neptune-plugins/blob/9a3061542c0c674639f386f6bee93820813af42c/plugins/TidalTags/src/Settings.ts#L8-L11

**Comment by Inrixia** [comment]
Yep that's stupid of me. Thanks for catching this @twnlink
