### ISSUE TITLE
MediaItems type is no longer a im.Map<string, MediaItem>

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune#14]
getState().content.mediaItems is now a number indexed object not a Map
![image](https://github.com/uwu/neptune/assets/6373693/b2000eb4-5b0a-4d03-8242-e486ea1d468b)

Unsure what else this applies to.

Found this when debugging the cause of https://github.com/Inrixia/neptune-plugins/issues/15

**Comment by twnlink** [comment]
Should be accounted for.
