### ISSUE TITLE
Can't install Neptune on Tidal Ver. 2.36

### ISSUE THREAD

**Issue by RoSeN16** [uwu/neptune#18]
Hello!

Just found neptune and was gonna give it a go but when i press "Install Neptune" i do not get the neptune settings options in Tidal. i've tried reinstalling Tidal (Not the Windows store version) and installning Neptune again but that did not work eiter. Im on Windows 11 if that matters at all.

**Comment by SigillSRGL** [comment]
i 2nd this. exact same issue, Running win10 64bit. TIDAL ver. 2.36.2

Running the neptune installer opens the webinstaller as expected but clicking on install instantly pops-up the confirmation but no neptune settings in the app. tried running with admin, tidal closed and open but nothing.

**Comment by Kvvanjung** [comment]
Same here

**Comment by awesmium** [comment]
having the same issue with the installer, checked permissions, antivirus, clean install, if it was installing in a weird location but couldnt find anything

[ 2.36.2.54-release (W: 2024.02.21-79-ff5df8393da8292e8fc87f10388130c61db07a5e) (NP: NA) ]

**Comment by Inrixia** [comment]
I've had a few people install it without issue recently so this may no longer be a problem.

If it's still not working I suggest trying to do a clean install and going to where the tidal exe is and ensuring all versions are deleted as sometimes previous versions can stick around.

**Comment by MinaPT** [comment]
hey, im still having all the same issues even with a fresh install 

[ 2.36.2.54-release (W: 2024.04.30-90-f46d10aa0c63a99c85f7b36e1b84efc94c1c5e45) (NP: 3.1.4.221)

**Comment by Crypto-Spartan** [comment]
I was able to install neptune, but i can't enable any of the plugins that i installed

**Comment by twnlink** [comment]
should work lol
