### ISSUE TITLE
Possible to get Sample Rate/Bit Depth/Bitrate? 

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune#2]
I have had a look and it doesn't appear that thus information is avalible even for the currently playing song atleast in the redux store.

But maybe you have a better idea of if it's possible to get at it somehow, do you think it's possible or is it simply not accessible?

**Comment by twnlink** [comment]
Unfortunately, after looking through everything, it doesn't appear that TIDAL exposes any APIs that'd allow you to get that information. I'd suggest digging through the app.(hash).js file in the sources tab in devtools, and if you find anything that'd need a hook to expose it before the app runs I can add it to neptune.

**Comment by Inrixia** [comment]
Yea, I know that the information is only available by whatever is actually handling playback of the files but afik that's not done in js but a seperate process so isn't accessible at all.

Thanks for checking
