### ISSUE TITLE
Plugin Toggle Button Is Dark In Color

### ISSUE THREAD

**Issue by Jasser1999** [uwu/neptune#21]
Tidal Ver 2.36.2

Newest Tidal update made just the plugins enable button go from white to black making a little hard to see . 

![image](https://github.com/uwu/neptune/assets/155720060/7e0c4701-c0e9-4414-8a6f-554e3a342226)

**Comment by twnlink** [comment]
Working on it 👍🏻

**Comment by twnlink** [comment]
This should be fixed in the latest version.
