### ISSUE TITLE
Neptune doesn't work for Tidal 2.37.8.59-release?

### ISSUE THREAD

**Issue by arturszolke** [uwu/neptune#24]
When I run the installer, nothing happens. There is no Neptune options in Tidal.

**Comment by iSlidex** [comment]
I know this is closed but I had the same issue, I use ad blocker and disabling it resolved the issue.

**Comment by arturszolke** [comment]
To be honest, I should leave here some message. For my case, I had somehow installed two instances of Tidal. I removed both, then installed completely from scratch. Then it worked.
