### ISSUE TITLE
Neptune: page not found.

### ISSUE THREAD

**Issue by CurtAD** [uwu/neptune#26]
Hello. I was going to Tidal today to find a page not found error message on my screen. There was an update today and after updating the app, it triggered this error message when clicking neptune settings in the dropdown on my user settings.

![The page doesn't exist](https://github.com/uwu/neptune/assets/54776929/4d94988b-2aec-4ce4-bc45-42bd43daeb76)

I also went into the console logs and found these error messages on the screen. Failed to load resource: the server responded with a status 403 error.
![Errors](https://github.com/uwu/neptune/assets/54776929/cdf07d2c-65e9-4e42-9219-38bbbf895d24)

Just thought I'd bring it to your attention.
Thanks.

**Comment by twnlink** [comment]
Working on it.

**Comment by twnlink** [comment]
Fixed in c73d95c.
