### ISSUE TITLE
TIDAL Staging

### ISSUE THREAD

**Issue by wont-stream** [uwu/neptune#28]
Was digging through DNS records and found `desktop.stage.tidal.com` which as implies, seems to be the beta version of the desktop app.

I can't find any mentions of it, and only change I can visibly see is a beta badge at the top left.

I was wondering if you had any info on this, and if it was in your interest to add some type of toggle for it with neptune?

I've written a guide to get it working with neptune- [gist](https://gist.github.com/wont-stream/9a622264c9cc2f7227ee9a264c6d610a)

Thanks.

edit: spelling

**Comment by wont-stream** [comment]
I've found another difference -- in the apps settings it has another tab "Debug Menu" which seems to be a native way to toggle experiments, like the plugin you've made.

**Comment by twnlink** [comment]
This is the dev version of the TIDAL client. TLDR: It's the newest possible build.
You can also update the app to the Beta version that uses this URL by setting the update url to `https://download.tidal.com/desktop/windows/beta/`
One way to do this is to run `require("electron").autoUpdater.updateURL = (BETA URL HERE)` and calling `autoUpdater.checkForUpdates()`.
This will break the desktop app.
