### ISSUE TITLE
Replace Playlist Tracks With Latest Release 

### ISSUE THREAD

**Issue by Mist3rChristopher** [uwu/neptune#38]
This would be a slight variation to RealMAX, but instead it looks for 'upgraded' versions of songs in general - not just just in terms of quality.

For example: days, weeks or even months before an album is released, an artist will release a single, which will subsequently get added to one of my playlists. And this is where my OCD kicks in - but once the album has been released, I then scan through my playlists and replace all the singles with the album version. I also do the same thing if a remaster, expanded or deluxe edition is then later released.

If, somehow, there was a way of expanded the RealMAX search to scan tracks and playlists for newer released remasters via release date maybe, and not just the maximum quality that would be AMAZING. Super thanks!

**Comment by twnlink** [comment]
While I appreciate the request, this is the wrong repository for this! Inrixia/neptune-plugins is what you're looking for.
