### ISSUE TITLE
NixOS package/module

### ISSUE THREAD

**Issue by xaiyadev** [uwu/neptune#40]
It would be a great feature if there were an option for a NixOS module or package. 

I might create a pull request myself in the near future.
Adding a flake for packaging would be enough for me.

**Comment by twnlink** [comment]
I'd gladly accept that PR if you make it.

**Comment by BreakingTV** [comment]
@twnlink 

I am almost done with the implementation.
I already made the package and it could be used, now I am working on the module system. 
A feature I want to add is that you can install themes and plugins in Nix itself with the url

For that I would like to understand from where you get your PluginStore
https://github.com/uwu/neptune/blob/13d0bc6197a798d1c98876601be0c3f59bd4fd3c/src/api/plugins.js#L9

I only find calls for it and how to add stuff or remove etc etc, but never where it is stored
Is it cached somehow?
I need that information so I can add it to the NixOS module options,

**Comment by BreakingTV** [comment]
Okay, after some time I finally found it ^^
This is my my bad

**Comment by twnlink** [comment]
> Okay, after some time I finally found it ^^
> This is my bad
> 
> But isnt it smarter saving the plugins in a json and/or files?
> Managing and working with these them would be more easier then, or am I seeing something wrong?

Storing them in IDB ensures we don't need full filesystem access. If I ever wanted to port neptune to the web client, the plugin system would just work out of the box.

**Comment by BreakingTV** [comment]
Okay got it!
Sadly with that, I cant make a NixOS module because I cant access the database

Maybe I do find a solution in the near future, until then I will make the pull request without the modules
