### ISSUE TITLE
Uploading local plugins does not work

### ISSUE THREAD

**Issue by xaiyadev** [uwu/neptune#44]
Right now I am trying to develop a plugin for neptune, I wrote a simple console.log and build it with "pnpm run build"
Then I clicked on the upload file and tried adding the build file into the plugin, but nothing really seems to work it is always "Failed to parse mainfest"

After looking into the code I seem to find that it searches for the manifest in the javascript, but in the local file the manifest and the js file are completly seperated

Am I missing something?
If yes, would it be helpfull to add it to the README?

**Comment by twnlink** [comment]
Local plugins don't require a build step.
Encode your manifest by putting it at the top as a comment:
`/*
{
  "name": "plugin name",
  "author": "plugin author"
  "description": "plugin description"
}
*/`
