### ISSUE TITLE
Tidal no longer loads with Neptune installed

### ISSUE THREAD

**Issue by Ro-Tang-Clan** [uwu/neptune#8]
I had Neptune working perfectly fine until I tried to load it up today and the app doesn't load as long as Neptune is installed. If I uninstall Neptune Tidal runs perfectly fine in vanilla state, however as soon as I install Neptune again, Tidal no longer works. Video [here](https://streamable.com/oattl2) for context.

Running Tidal version 2.34.3.

Any help appreciated, thanks!

**Comment by twnlink** [comment]
I'm currently working on a fix :)

**Comment by Ro-Tang-Clan** [comment]
> I'm currently working on a fix :)

Oh wow that's quick. You're a legend mate! I'll patiently wait for an update then, cheers! :)

**Comment by twnlink** [comment]
This issue has been fixed. Wait about 10 minutes before reinstalling neptune and restarting the client and it should work.
